# Name of the snippet:
TARGET_NAME = program

# Specify all source files:
SOURCES = main.c
SOURCES += dll.c
# SOURCES +=

# Specify all source files:
#SOURCES_TESTS = ../tests/day01.c
# SOURCES_TESTS +=

# Specify all include paths:
INCLUDE_PATHS  = .
INCLUDE_PATHS += ../utils

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
